### ISSUE TITLE
Source Code? - Malware Likely.

### ISSUE THREAD

**Issue by newrecycle** [NxRoot/SynapseKiller#3]
Why not upload the source code and build files. Escpecially when the virustotal report looks like this: https://www.virustotal.com/gui/file/840313a579969f66e184e0ef846b402e4ea5a9ec58d28b7e19b1e12a8dc33e01/detection

Cool project, I hate synapse as much as you. 
I hope you will **actually** release it so I can give it a try!

**Comment by NxRoot** [comment]
Any code that deals with processes will be flagged as a potential virus, since the app doesn't have a signing certificate (which you have to pay for) it will always be considered untrusted.

The virus total analyzes for potential dangers, if you upload any C/C++ compiled executable to virus total, they will always show up as potential virus.

Anyway, If it was a virus, the windows AV would stop it and remove it immediately at execution. 

The reason I don't share the source code is because there's no point on doing that, people need something to deal with synapse processes, not a full page tutorial on how to run the source code.

**Comment by newrecycle** [comment]
I appreciate your sentiment that you'd like it to be easy for people to use but if you've already got binaries built, why not put them under the releases tab so they're still easily accessible? 

It would take only as long as your internet connection takes to upload it to the repository.

Not only would it become more popular and make it a lot easier for more people to use it comfortably, but you'd even get feedback and new features from the community! 

I feel like maybe if you were scared of someone stealing your work and idea i'd understand. but saying you'll only release the binaries because "it's easier for people" just makes me more suspicious that there is something in there...

**Comment by NxRoot** [comment]
Sharing source code is the first step to get something patched. 
You don't like it? Don't use it.
